// Code generated by templ@v0.2.334 DO NOT EDIT.

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/ItsNotGoodName/smtpbridge/internal/models"
	"github.com/ItsNotGoodName/smtpbridge/web/routes"
)

type AttachmentCardProps struct {
	Attachment models.Attachment
}

func AttachmentCard(props AttachmentCardProps) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div class=\"card card-compact bg-base-100 border-base-200 w-full border sm:w-80\">")
		if err != nil {
			return err
		}
		if props.Attachment.IsImage() {
			_, err = templBuffer.WriteString("<figure><img src=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(routes.AttachmentFile(props.Attachment.FileName()).URLString()))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" alt=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(props.Attachment.Name))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"></figure>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("<div class=\"card-body\"><h2 class=\"card-title break-all\">")
		if err != nil {
			return err
		}
		var var_2 string = props.Attachment.Name
		_, err = templBuffer.WriteString(templ.EscapeString(var_2))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</h2><div class=\"card-actions justify-end\"><a href=\"")
		if err != nil {
			return err
		}
		var var_3 templ.SafeURL = routes.AttachmentFile(props.Attachment.FileName()).URLQuery("download=1")
		_, err = templBuffer.WriteString(templ.EscapeString(string(var_3)))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" class=\"btn btn-primary\">")
		if err != nil {
			return err
		}
		var_4 := `Download`
		_, err = templBuffer.WriteString(var_4)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("</a></div></div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
