//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Messages = newMessagesTable("", "messages", "")

type messagesTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	From      sqlite.ColumnString
	To        sqlite.ColumnString
	Subject   sqlite.ColumnString
	Text      sqlite.ColumnString
	HTML      sqlite.ColumnString
	Date      sqlite.ColumnTimestamp
	CreatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type MessagesTable struct {
	messagesTable

	EXCLUDED messagesTable
}

// AS creates new MessagesTable with assigned alias
func (a MessagesTable) AS(alias string) *MessagesTable {
	return newMessagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MessagesTable with assigned schema name
func (a MessagesTable) FromSchema(schemaName string) *MessagesTable {
	return newMessagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MessagesTable with assigned table prefix
func (a MessagesTable) WithPrefix(prefix string) *MessagesTable {
	return newMessagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MessagesTable with assigned table suffix
func (a MessagesTable) WithSuffix(suffix string) *MessagesTable {
	return newMessagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMessagesTable(schemaName, tableName, alias string) *MessagesTable {
	return &MessagesTable{
		messagesTable: newMessagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newMessagesTableImpl("", "excluded", ""),
	}
}

func newMessagesTableImpl(schemaName, tableName, alias string) messagesTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		FromColumn      = sqlite.StringColumn("from")
		ToColumn        = sqlite.StringColumn("to")
		SubjectColumn   = sqlite.StringColumn("subject")
		TextColumn      = sqlite.StringColumn("text")
		HTMLColumn      = sqlite.StringColumn("html")
		DateColumn      = sqlite.TimestampColumn("date")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		allColumns      = sqlite.ColumnList{IDColumn, FromColumn, ToColumn, SubjectColumn, TextColumn, HTMLColumn, DateColumn, CreatedAtColumn}
		mutableColumns  = sqlite.ColumnList{FromColumn, ToColumn, SubjectColumn, TextColumn, HTMLColumn, DateColumn, CreatedAtColumn}
	)

	return messagesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		From:      FromColumn,
		To:        ToColumn,
		Subject:   SubjectColumn,
		Text:      TextColumn,
		HTML:      HTMLColumn,
		Date:      DateColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
