// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package queries

import (
	"database/sql"
	"time"
)

type Attachment struct {
	ID        int64
	MessageID sql.NullInt64
	Name      string
	Mime      string
	Extension string
}

type Endpoint struct {
	ID                int64
	Internal          bool
	InternalID        string
	Name              string
	AttachmentDisable bool
	TextDisable       bool
	BodyTemplate      string
	Kind              string
	Config            interface{}
	UpdatedAt         time.Time
	CreatedAt         time.Time
}

type Message struct {
	ID        int64
	From      string
	To        interface{}
	Subject   string
	Text      string
	Html      string
	Date      time.Time
	CreatedAt time.Time
}

type Rule struct {
	ID         int64
	Internal   bool
	InternalID string
	Name       string
	Template   string
	Enable     bool
	UpdatedAt  time.Time
	CreatedAt  time.Time
}

type RulesToEndpoint struct {
	Internal   bool
	RuleID     int64
	EndpointID string
	UpdatedAt  time.Time
	CreatedAt  time.Time
}
