//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Attachments struct {
	ID        int32 `sql:"primary_key"`
	MessageID int32
	Name      string
	Mime      string
	Extension string
}
