//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Endpoints struct {
	ID                int32 `sql:"primary_key"`
	Internal          bool
	InternalID        string
	Name              string
	AttachmentDisable bool
	TextDisable       bool
	BodyTemplate      string
	Kind              string
	Config            string
	UpdatedAt         time.Time
	CreatedAt         time.Time
}
