//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RulesToEndpoints struct {
	Internal   bool
	RuleID     int32
	EndpointID string
	UpdatedAt  time.Time
	CreatedAt  time.Time
}
